backend:
  name: git-gateway
  branch: main        # of jouw branch naam

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Paginas"
    files:
      - file: "content/home.json"
        label: "Homepage"
        name: "home"
        format: "json"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Tekst", name: "body", widget: "markdown" }
